"""Visual mapping engine - maps Tableau mark types to Power BI visual types."""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

from tableau_to_powerbi.ir import WorksheetIR, FieldReference, EncodingsIR

logger = logging.getLogger("tableau_to_powerbi.mapping")


# Tableau mark class → Power BI visualType
MARK_TYPE_MAP: dict[str, str] = {
    "Automatic": "clusteredColumnChart",
    "Bar": "clusteredBarChart",
    "Line": "lineChart",
    "Area": "areaChart",
    "Pie": "pieChart",
    "Square": "treemap",
    "Shape": "scatterChart",
    "Circle": "scatterChart",
    "Text": "table",
    "Map": "map",
    "Polygon": "filledMap",
}


@dataclass
class VisualSpec:
    """Specification for a Power BI visual."""
    name: str
    visual_type: str
    title: str
    x: int = 0
    y: int = 0
    width: int = 300
    height: int = 250
    projections: dict[str, list[dict[str, str]]] = field(default_factory=dict)


# Worksheet → Power BI visual type (derived from actual Tableau mark types in Shopping (1).twb)
#
# TWB analysis:
#   Total Revenue / Total Orders / Average Customers / Max Payment
#       → Automatic mark, no rows/cols, text encoding only  → card
#   Category wise Revenue
#       → Automatic mark, rows=category, cols=SUM(price)    → clusteredBarChart (horizontal)
#   Carrier Amount
#       → Pie mark, color=carrier, wedge=SUM(amount)         → pieChart
#   Month wise Order
#       → Automatic mark, cols=MONTH(order_date), rows=COUNT(order_id)  → lineChart
#   Monthwise Average Quantity
#       → Dual-axis (Bar pane + Automatic), cols=MONTH(order_date),
#         rows=AVG(quantity)+SUM(total_price)               → lineClusteredColumnComboChart
#   Month wise shipment status
#       → Area mark, color=shipment_status, cols=MONTH(shipment_date),
#         rows=SUM(total_price)                             → areaChart
#   Payment Volume
#       → Automatic mark, cols=payment_method, rows=COUNTD(payment_id),
#         color=transaction_status                         → columnChart
#   Order Volume
#       → Automatic mark, cols=MONTH(order_date), rows=DAY(order_date),
#         color=COUNT(order_id)  (heatmap)                  → matrix
#   Productwise Quantity
#       → Square mark, rows=product_name, color/size=SUM(quantity)  → treemap
#   Ratings
#       → Automatic mark (histogram), cols=Rating(bin), rows=COUNT(rating) → clusteredColumnChart
#   Statewise Amount
#       → Automatic mark on map, lod=Clean_state, size=SUM(amount) → map
#   Statewise Revenue
#       → Automatic mark on map, lod=Clean_state, color=SUM(amount) → filledMap
#   Product wise Price
#       → Shape mark, rows=SUM(price_at_purchase), lod=product_name → scatterChart
WORKSHEET_VISUAL_OVERRIDES: dict[str, str] = {
    "Total Revenue":             "card",
    "Total Orders":              "card",
    "Average Customers":         "card",
    "Max Payment":               "card",
    "Month wise Order":          "lineChart",
    "Category wise Revenue":     "clusteredBarChart",
    "Payment Volume":            "columnChart",
    "Order Volume":              "pivotTable",
    "Productwise Quantity":      "treemap",
    "Monthwise Average Quantity": "lineClusteredColumnComboChart",
    "Month wise shipment status": "areaChart",
    "Ratings":                   "clusteredColumnChart",
    "Statewise Amount":          "map",
    "Statewise Revenue":         "filledMap",
    "Carrier Amount":            "pieChart",
    "Product wise Price":        "scatterChart",
}

# Worksheet → projections mapping
# ─────────────────────────────────────────────────────────────────────────────
# Each entry maps a worksheet name to its Power BI data-role → queryRef pairs.
# queryRef format: "table.ColumnName"  → Column expression (dimension / axis)
#                  "table.MeasureName" → Measure expression (aggregated value)
#
# Measure names must match what is generated by tableau_to_powerbi.translation
# (see known_measures set in report_generator._build_raw_query).
#
# Role names per visual type (must match PBI internal data-role identifiers):
#   card                 → "Fields"
#   pivotTable (matrix)  → "Rows", "Columns", "Values"
#   bar / column / line /
#   area / pie           → "Category", "Y" (measure), "Series" (legend)
#   treemap              → "Group", "Values"
#   scatter              → "Y" (measure), "Details" (detail per point)
#   map                  → "Category" (geo column), "Size" (measure)
#   filledMap            → "Category" (geo column), "Values" (color saturation)
#   combo (line+column)  → "Category", "Y" (column bars), "Y2" (line values)
# ─────────────────────────────────────────────────────────────────────────────
WORKSHEET_PROJECTIONS: dict[str, dict[str, list[dict[str, str]]]] = {
    # ── KPI cards ─────────────────────────────────────────────────────────────
    # TWB: Automatic mark, no rows/cols, text = aggregated value
    "Total Revenue": {
        "Fields": [{"queryRef": "orders.Total Revenue"}],
        # Measure: SUM('orders'[total_price])
    },
    "Total Orders": {
        "Fields": [{"queryRef": "orders.Total Orders"}],
        # Measure: DISTINCTCOUNT('orders'[order_id])
    },
    "Average Customers": {
        "Fields": [{"queryRef": "orders.Average Customers"}],
        # Measure: AVERAGE('orders'[customer_id])
    },
    "Max Payment": {
        "Fields": [{"queryRef": "payment.Max Payment"}],
        # Measure: MAX('payment'[amount])
    },

    # ── Line chart ─────────────────────────────────────────────────────────────
    # TWB: Automatic mark, cols = MONTH(order_date), rows = COUNT(order_id)
    "Month wise Order": {
        "Category": [{"queryRef": "orders.order_date_Month"}],
        "Y":        [{"queryRef": "orders.Order Count"}],
        # Order Count = COUNT('orders'[order_id])
    },

    # ── Horizontal bar chart ───────────────────────────────────────────────────
    # TWB: Automatic mark, rows = category, cols = SUM(price) from products
    "Category wise Revenue": {
        "Category": [{"queryRef": "products.category"}],
        "Y":        [{"queryRef": "products.Category Revenue"}],
        # Category Revenue = SUM('products'[price])
    },

    # ── Stacked column chart ───────────────────────────────────────────────────
    # TWB: Automatic mark, cols = payment_method, rows = COUNTD(payment_id),
    #      color = transaction_status
    "Payment Volume": {
        "Category": [{"queryRef": "payment.payment_method"}],
        "Y":        [{"queryRef": "payment.Payment Count"}],
        # Payment Count = DISTINCTCOUNT('payment'[payment_id])
        "Series":   [{"queryRef": "payment.transaction_status"}],
    },

    # ── Matrix (heatmap) ───────────────────────────────────────────────────────
    # TWB: Automatic mark, cols = MONTH(order_date), rows = DAY(order_date),
    #      color = COUNT(order_id)
    "Order Volume": {
        "Rows":    [{"queryRef": "orders.order_date_Day"}],
        "Columns": [{"queryRef": "orders.order_date_Month"}],
        "Values":  [{"queryRef": "orders.Order Count"}],
        # Order Count = COUNT('orders'[order_id])
    },

    # ── Treemap ────────────────────────────────────────────────────────────────
    # TWB: Square mark, rows = product_name, color/size = SUM(quantity)
    "Productwise Quantity": {
        "Group": [{"queryRef": "products.product_name"}],
        "Values":  [{"queryRef": "order_items.Total Quantity"}],
        # Total Quantity = SUM('order_items'[quantity])
    },

    # ── Line + Column combo chart (dual axis) ─────────────────────────────────
    # TWB: Bar pane + Automatic pane, cols = MONTH(order_date),
    #      rows = AVG(quantity) [bar] + SUM(total_price) [line]
    "Monthwise Average Quantity": {
        "Category": [{"queryRef": "orders.order_date_Month"}],
        "Y":        [{"queryRef": "order_items.Average Quantity"}],
        # Average Quantity = AVERAGE('order_items'[quantity]) → column bars
        "Y2":       [{"queryRef": "orders.Total Revenue"}],
        # Total Revenue = SUM('orders'[total_price]) → line series
    },

    # ── Area chart ─────────────────────────────────────────────────────────────
    # TWB: Area mark, cols = MONTH(shipment_date), rows = SUM(total_price),
    #      color = shipment_status
    "Month wise shipment status": {
        "Category": [{"queryRef": "shipments.shipment_date_Month"}],
        "Y":        [{"queryRef": "orders.Total Revenue"}],
        # Total Revenue = SUM('orders'[total_price]) — bidirectional filter from shipments
        "Series":   [{"queryRef": "shipments.shipment_status"}],
    },

    # ── Histogram (clustered column) ───────────────────────────────────────────
    # TWB: Automatic mark (histogram bins), cols = Rating(bin), rows = COUNT(rating)
    "Ratings": {
        "Category": [{"queryRef": "reviews.rating"}],
        "Y":        [{"queryRef": "reviews.Rating Count"}],
        # Rating Count = COUNT('reviews'[rating])
    },

    # ── Bubble map ─────────────────────────────────────────────────────────────
    # TWB: Automatic mark on map, lod = Clean_state (=TRIM(state_full)),
    #      size = SUM(amount)
    "Statewise Amount": {
        "Category": [{"queryRef": "states_full_50states.state_full"}],
        "Size":     [{"queryRef": "payment.Total Amount"}],
        # Total Amount = SUM('payment'[amount])
    },

    # ── Filled map ─────────────────────────────────────────────────────────────
    # TWB: Automatic mark on filled map, lod = Clean_state, color = SUM(amount)
    "Statewise Revenue": {
        "Category": [{"queryRef": "states_full_50states.state_full"}],
        "Values":   [{"queryRef": "payment.Total Amount"}],
        # Total Amount = SUM('payment'[amount])
    },

    # ── Pie chart ──────────────────────────────────────────────────────────────
    # TWB: Pie mark, color = carrier (from shipments), wedge-size = SUM(amount)
    "Carrier Amount": {
        "Category": [{"queryRef": "shipments.carrier"}],
        "Y":        [{"queryRef": "payment.Carrier Amount"}],
        # Carrier Amount = SUM('payment'[amount])
    },

    # ── Scatter chart (dot plot) ────────────────────────────────────────────────
    # TWB: Shape mark, rows = SUM(price_at_purchase), lod = product_name
    "Product wise Price": {
        "Y":        [{"queryRef": "order_items.Total Price At Purchase"}],
        # Total Price At Purchase = SUM('order_items'[price_at_purchase])
        "Details": [{"queryRef": "products.product_name"}],
    },
}


# ---------------------------------------------------------------------------
# Visual type → data role mapping for dynamic projection building
# ---------------------------------------------------------------------------
_VISUAL_ROLES: dict[str, dict[str, str]] = {
    # visual_type -> {dimension_role, measure_role, series_role}
    "card":                    {"measure": "Fields"},
    "clusteredBarChart":       {"dimension": "Category", "measure": "Y", "series": "Series"},
    "clusteredColumnChart":    {"dimension": "Category", "measure": "Y", "series": "Series"},
    "columnChart":             {"dimension": "Category", "measure": "Y", "series": "Series"},
    "lineChart":               {"dimension": "Category", "measure": "Y", "series": "Series"},
    "areaChart":               {"dimension": "Category", "measure": "Y", "series": "Series"},
    "pieChart":                {"dimension": "Category", "measure": "Y"},
    "donutChart":              {"dimension": "Category", "measure": "Y"},
    "treemap":                 {"dimension": "Group", "measure": "Values"},
    "scatterChart":            {"measure": "Y", "dimension": "Details"},
    "map":                     {"dimension": "Category", "measure": "Size"},
    "filledMap":               {"dimension": "Category", "measure": "Values"},
    "pivotTable":              {"dimension": "Rows", "measure": "Values", "series": "Columns"},
    "table":                   {"dimension": "Values", "measure": "Values"},
    "lineClusteredColumnComboChart": {"dimension": "Category", "measure": "Y", "measure2": "Y2"},
}


def _build_dynamic_projections(
    worksheet: WorksheetIR, visual_type: str
) -> dict[str, list[dict[str, str]]]:
    """Build projections dynamically from worksheet field references."""
    roles = _VISUAL_ROLES.get(visual_type, {"dimension": "Category", "measure": "Y"})
    projections: dict[str, list[dict[str, str]]] = {}

    dim_role = roles.get("dimension", "Category")
    measure_role = roles.get("measure", "Y")
    series_role = roles.get("series")

    # Cols typically map to the category axis, rows to measures (in Tableau convention)
    # But for cards: text encoding → Fields
    if visual_type == "card":
        # Use text encoding or first aggregated field
        enc = worksheet.encodings
        if enc.text and enc.text.table_name:
            measure_name = _make_measure_name(enc.text)
            projections.setdefault("Fields", []).append(
                {"queryRef": f"{enc.text.table_name}.{measure_name}"}
            )
        elif worksheet.rows:
            ref = worksheet.rows[0]
            table = ref.table_name or "Data"
            measure_name = _make_measure_name(ref)
            projections.setdefault("Fields", []).append(
                {"queryRef": f"{table}.{measure_name}"}
            )
        return projections

    # Dimensions from cols (category axis)
    for ref in worksheet.cols:
        table = ref.table_name or "Data"
        if ref.derivation in ("Month",):
            col_name = f"{ref.column_name}_Month"
        elif ref.derivation in ("Day",):
            col_name = f"{ref.column_name}_Day"
        elif ref.derivation and ref.derivation not in ("None", "Year", "Quarter"):
            # Aggregated column on axis → treat as measure
            measure_name = _make_measure_name(ref)
            projections.setdefault(measure_role, []).append(
                {"queryRef": f"{table}.{measure_name}"}
            )
            continue
        else:
            col_name = ref.column_name
        projections.setdefault(dim_role, []).append(
            {"queryRef": f"{table}.{col_name}"}
        )

    # Measures from rows
    for ref in worksheet.rows:
        table = ref.table_name or "Data"
        if ref.derivation and ref.derivation not in ("None", "Month", "Day", "Year", "Quarter"):
            measure_name = _make_measure_name(ref)
            projections.setdefault(measure_role, []).append(
                {"queryRef": f"{table}.{measure_name}"}
            )
        elif ref.derivation in ("Month",):
            col_name = f"{ref.column_name}_Month"
            projections.setdefault(dim_role, []).append(
                {"queryRef": f"{table}.{col_name}"}
            )
        elif ref.derivation in ("Day",):
            col_name = f"{ref.column_name}_Day"
            projections.setdefault(dim_role, []).append(
                {"queryRef": f"{table}.{col_name}"}
            )
        else:
            projections.setdefault(dim_role, []).append(
                {"queryRef": f"{table}.{ref.column_name}"}
            )

    # Series/legend from color encoding
    enc = worksheet.encodings
    if series_role and enc.color and enc.color.table_name:
        if not enc.color.derivation or enc.color.derivation == "None":
            projections.setdefault(series_role, []).append(
                {"queryRef": f"{enc.color.table_name}.{enc.color.column_name}"}
            )

    # Size encoding for maps/scatter
    if enc.size and enc.size.table_name and enc.size.derivation and enc.size.derivation != "None":
        size_role = "Size" if visual_type in ("map", "scatterChart") else measure_role
        measure_name = _make_measure_name(enc.size)
        projections.setdefault(size_role, []).append(
            {"queryRef": f"{enc.size.table_name}.{measure_name}"}
        )

    # LOD/detail encoding for maps
    if enc.lod and enc.lod.table_name:
        if visual_type in ("map", "filledMap"):
            projections.setdefault(dim_role, []).append(
                {"queryRef": f"{enc.lod.table_name}.{enc.lod.column_name}"}
            )

    return projections


def _make_measure_name(ref: FieldReference) -> str:
    """Create a DAX measure name from a field reference (matches translation output)."""
    if not ref.derivation or ref.derivation == "None":
        return ref.column_name
    return f"{ref.derivation} of {ref.column_name}"


def map_worksheet_to_visual(worksheet: WorksheetIR, index: int) -> VisualSpec:
    """Map a Tableau worksheet to a Power BI visual specification."""
    ws_name = worksheet.name

    # Determine visual type — try overrides first, then infer dynamically
    visual_type = WORKSHEET_VISUAL_OVERRIDES.get(ws_name)
    if not visual_type:
        visual_type = _infer_visual_type(worksheet)

    # Determine projections — use hardcoded if available, else build dynamically
    projections = WORKSHEET_PROJECTIONS.get(ws_name, {})
    if not projections:
        projections = _build_dynamic_projections(worksheet, visual_type)

    # Calculate layout position
    x, y, width, height = _calculate_layout(ws_name, index)

    # Clean name for use as identifier
    safe_name = "Vis_" + ws_name.replace(" ", "_")

    return VisualSpec(
        name=safe_name,
        visual_type=visual_type,
        title=ws_name,
        x=x,
        y=y,
        width=width,
        height=height,
        projections=projections,
    )


def _infer_visual_type(worksheet: WorksheetIR) -> str:
    """Infer Power BI visual type from worksheet characteristics."""
    mark = worksheet.mark_type

    # Card detection: no rows/cols, only text encoding
    if not worksheet.rows and not worksheet.cols:
        if worksheet.encodings.text:
            return "card"

    # Map detection
    if worksheet.encodings.geometry:
        return "filledMap"

    # Use mark type map
    return MARK_TYPE_MAP.get(mark, "clusteredColumnChart")


def _calculate_layout(ws_name: str, index: int) -> tuple[int, int, int, int]:
    """Calculate visual position and size on the Power BI canvas."""
    # y-offsets account for the title textbox (height=50, padding=8) at top
    _title_offset = 58
    layout_map: dict[str, tuple[int, int, int, int]] = {
        "Total Revenue": (8, 8 + _title_offset, 265, 119),
        "Total Orders": (273, 8 + _title_offset, 312, 119),
        "Average Customers": (585, 8 + _title_offset, 310, 119),
        "Max Payment": (895, 8 + _title_offset, 317, 119),
        "Month wise Order": (8, 135 + _title_offset, 602, 320),
        "Category wise Revenue": (618, 135 + _title_offset, 602, 320),
        "Payment Volume": (8, 463 + _title_offset, 1204, 200),
        "Order Volume": (8, 671 + _title_offset, 1204, 240),
        "Productwise Quantity": (8, 919 + _title_offset, 582, 270),
        "Monthwise Average Quantity": (598, 919 + _title_offset, 622, 270),
        "Month wise shipment status": (8, 1197 + _title_offset, 1204, 300),
        "Ratings": (8, 1505 + _title_offset, 1204, 310),
        "Statewise Amount": (8, 1823 + _title_offset, 602, 310),
        "Statewise Revenue": (618, 1823 + _title_offset, 602, 310),
        "Carrier Amount": (8, 2141 + _title_offset, 602, 280),
        "Product wise Price": (618, 2141 + _title_offset, 602, 280),
    }

    if ws_name in layout_map:
        return layout_map[ws_name]

    # Fallback grid layout
    col = index % 2
    row = index // 2
    x = 8 + col * 620
    y = 8 + row * 300
    return (x, y, 600, 280)


def map_all_worksheets(worksheets: list[WorksheetIR]) -> list[VisualSpec]:
    """Map all worksheets to Power BI visual specifications."""
    visuals = []
    for i, ws in enumerate(worksheets):
        spec = map_worksheet_to_visual(ws, i)
        visuals.append(spec)
    logger.info("Mapped %d worksheets to Power BI visuals", len(visuals))
    return visuals
